movie_library/routes.py
from datetime import datetime, date
import uuid
from flask import (
    Blueprint,
    flash, 
    redirect, 
    render_template, 
    url_for, 
    request, 
    session, 
    current_app,
    )
from movie_library.forms import LoginForm, MovieForm, ExtendedMovieForm, PasswordForm, RegisterForm, UserForm
from movie_library.models import Movie, User, login_required
from movie_library.modules import check_movie_belong_to_current_user, save_user_to_session 

from dataclasses import asdict
from passlib.hash import pbkdf2_sha256
from slugify import slugify
from werkzeug.utils import secure_filename
import os 


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

## Homepage (show list movie)
@pages.route("/")
def index():
    user = session.get("current_user")
    if user != None:
        movie_ids = user['movies']
    else:
        movie_ids = []
    list_movie = [Movie(**movie) for movie in current_app.db.Movie.find({"_id": {"$in" : movie_ids}})]
    return render_template(
        "index.html",
        title="Movies Watchlist",
        th_movie_data = list_movie
    )

## Account (show and edit profile, password)
@pages.route("/profile", methods = ["GET", "POST"])
@login_required
def profile():
    current_user = session.get("current_user")
    _id = current_user['_id']
    form = UserForm(obj = User(**current_user))

    lst_movies = list(current_app.db.Movie.find({"_id":{"$in": current_user['movies']}}))
    lst_movie_names = [movie['title'] for movie in lst_movies]
    form.movies_names.data = lst_movie_names
    
    avatar_path = os.path.dirname(os.path.realpath(__file__))+"/static/img/avatar/"
    lst_img = [f for f in os.listdir(avatar_path) if os.path.isfile(os.path.join(avatar_path, f))]
        
    current_avatar = ""
    for img in lst_img:
        if _id in img:
            current_avatar = img
            break

    if form.validate_on_submit():
        user = dict(
            name = form.name.data,
            dob = form.dob.data,
            nationality = form.nationality.data,
        )
        current_app.db.User.update_one({"_id": _id}, {"$set": user})
        save_user_to_session()

        f = form.avatar_file.data
        if f == None:
            return redirect(url_for('pages.index'))

        if current_avatar != "":
            print(avatar_path + current_avatar)
            os.remove(avatar_path + current_avatar)
            
        filename = secure_filename("ava" + _id + "." + f.filename.split(".")[-1])
        f.save(avatar_path+filename)
        return redirect(url_for('pages.index'))

    return render_template("edit_user.html",
    title="My profile",
    form = form,
    th_current_avatar = current_avatar)

@pages.route("/change_password", methods = ["GET", "POST"])
@login_required
def change_password():
    current_user = session.get("current_user")
    _id = current_user['_id']
    form = PasswordForm()

    if form.validate_on_submit():
        form_data = {
            'old': form.old.data,
            'new1': form.new1.data,
            'new2': form.new2.data
        }
        if pbkdf2_sha256.verify(form_data['old'], current_user['password']):
            current_app.db.User.update_one({"_id": _id}, {"$set": {"password": pbkdf2_sha256.hash(form_data['new1'])}})
            save_user_to_session()
            flash("Password changed.", "success")
            return redirect(url_for('pages.index'))
        else:
            flash("Wrong current password. Try again!", "danger")
            return redirect(url_for('pages.change_password'))

    return render_template("edit_password.html",
    title="Change password",
    form = form)

## Add movie
@pages.route("/add", methods = ["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()
    if form.validate_on_submit():
        movie = Movie(
            _id = uuid.uuid4().hex,
            title = form.title.data,
            director = form.director.data,
            year = form.year.data
        )
        current_app.db.Movie.insert_one(asdict(movie))
        current_app.db.User.update_one({"email": session.get("email")}, {"$push": {"movies": movie._id}})
        save_user_to_session()
        return redirect(url_for('pages.movie', _id = movie._id))

    return render_template("new_movie.html",
    title="Add movie",
    form = form)

## Show movie, edit movie information
@pages.route("/movie/<string:_id>")
@login_required
def movie(_id):
    check = check_movie_belong_to_current_user(_id)
    current_movie = list(current_app.db.Movie.find({"_id": _id}))[0]
    movie = Movie(**current_movie)
    link_qr = "https://thang-pham-multi-purpose-app.herokuapp.com/movie/"+_id
    slugified_title = slugify(movie.title)
    return render_template(
        "movie_details.html", 
        title = movie.title,
        th_movie = movie, 
        th_check = check, 
        th_link_qr = link_qr,
        th_slugified_title = slugified_title
    )

@pages.route("/movie/<string:_id>/rating/<int:rating>")
@login_required
def rating(_id, rating):
    check = check_movie_belong_to_current_user(_id)
    if not check:
        return redirect(url_for('pages.movie', _id = _id))
    current_app.db.Movie.update_one({"_id": _id}, {"$set": {"rating": rating}})
    return redirect(url_for('pages.movie', _id = _id))

@pages.route("/movie/<string:_id>/watch_date/")
@login_required
def watch_date(_id):
    check = check_movie_belong_to_current_user(_id)
    if not check:
        return redirect(url_for('pages.movie', _id = _id))
    current_app.db.Movie.update_one({"_id": _id}, {"$set": {"last_watched": datetime.today().strftime("%b %d %Y")}})    
    return redirect(url_for('pages.movie', _id = _id))

@pages.route("/edit/<string:_id>/", methods = ["GET", "POST"])
@login_required
def edit_movie(_id):
    check = check_movie_belong_to_current_user(_id)
    if not check:
        return redirect(url_for('pages.movie', _id = _id))

    current_movie = list(current_app.db.Movie.find({"_id": _id}))[0]
    movie = Movie(**current_movie)
    form = ExtendedMovieForm(obj = movie)

    if form.validate_on_submit():
        movie = dict(
            title = form.title.data,
            director = form.director.data,
            year = form.year.data,
            cast = form.cast.data,
            series = form.series.data,
            tags = form.tags.data,
            description = form.description.data,
            video_link = form.video_link.data,
        )

        current_app.db.Movie.update_one({"_id": _id}, {"$set": movie})
        return redirect(url_for('pages.movie', _id = _id))

    return render_template("edit_movie.html",
    title=movie.title,
    th_movie = movie,
    form = form)

## Register and Login/Logout account
@pages.route("/register", methods = ['GET','POST'])
def register():
    if session.get("email"):
        return redirect("/")
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            _id = uuid.uuid4().hex,
            email = form.email.data,
            password = pbkdf2_sha256.hash(form.password.data)
        )
        lst_email = [u['email'] for u in list(current_app.db.User.find({}, {"email": 1}))]
        if user.email in lst_email:
            flash("This email had been registerd already. Use another email!", "danger")
            return redirect("/register")
        current_app.db.User.insert_one(asdict(user))
        flash("Registered Successfully!", "success")
        return redirect("/login")
    return render_template('register.html', th_form = form, title="Register")

@pages.route("/login", methods = ['GET','POST'])
def login():
    if session.get("email"):
        if session.get("url_bf_login") != None:
            url = session.get("url_bf_login")
            session["url_bf_login"] = None
            return redirect(url)
        return redirect("/")

    form = LoginForm()
    if form.validate_on_submit():
        login_dic = {
            'email' : form.email.data,
            'password': form.password.data
        }
        user = list(current_app.db.User.find({"email": login_dic['email']}))
        if len(user) > 0:
            if pbkdf2_sha256.verify(login_dic['password'], user[0]['password']):
                session['email'] = login_dic['email']
                save_user_to_session()
                return redirect(request.path)
        flash("Wrong email or password!", "danger")
    return render_template('login.html', th_form = form, title="Log in")

@pages.route("/logout")
def logout():
    session['email'] = None
    session['current_user'] = None
    return redirect("/")

# Switch light/dark mode
@pages.route("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == 'dark':
        current_theme = 'light'
    else:
        current_theme = 'dark'
    session['theme'] = current_theme

    return redirect(request.args.get("current_page"))

movie_library/templates/edit_movie.html
{% from "macros/fields.html" import render_text_field, render_area_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<form action="{{ url_for('pages.edit_movie', _id = th_movie._id) }}" class="form" novalidate method="post">
  <div class="form__container">
    {{ form.hidden_tag() }}
    {{ render_text_field(form.title) }}
    {{ render_text_field(form.director) }}
    {{ render_text_field(form.year) }}
    
    {{ render_area_field(form.cast) }}
    {{ render_area_field(form.series) }}
    {{ render_area_field(form.tags) }}

    {{ render_area_field(form.description) }}
    {{ render_text_field(form.video_link) }}

    <div>
      {{ form.submit(class_="button button--form")}}
    </div>
  </div>
</form>

{% endblock %}

movie_library/templates/edit_password.html
{% from "macros/fields.html" import render_text_field, render_area_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {%- for category, message in messages %}
      <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
  {% endfor %}
{% endwith %}

<form action="{{ url_for('pages.change_password') }}" class="form" novalidate method="post">
  <div class="form__container">
    {{ form.hidden_tag() }}
    {{ render_text_field(form.old) }}
    {{ render_text_field(form.new1) }}
    {{ render_text_field(form.new2) }}    
    <div>
      {{ form.submit(class_="button button--form")}}
    </div>
  </div>
</form>

{% endblock %}

movie_library/templates/edit_user.html
{% from "macros/fields.html" import render_text_field, render_area_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<form action="{{ url_for('pages.profile') }}" enctype="multipart/form-data" class="form" novalidate method="post">
  <div class="form__container">
    <img class="profile_avatar" src="{{ url_for('static', filename='img/avatar/'+th_current_avatar) }}" alt="You do not have an avatar yet!">
    {{ form.hidden_tag() }}
    {{ render_text_field(form.avatar_file) }}
    {{ render_text_field(form.name) }}
    {{ render_text_field(form.email) }}
    {{ render_text_field(form.dob) }}
    {{ render_text_field(form.nationality) }}
    
    {{ render_area_field(form.movies_names) }}
    <div>
      <a href="{{ url_for('pages.change_password') }}" class="button">Change password</a>
      {{ form.submit(class_="button button--form")}}
    </div>
  </div>
</form>

{% endblock %}

movie_library/templates/index.html
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/movies.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    {% with messages = get_flashed_messages(with_categories=true) %}
    {%- for category, message in messages %}
        <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
    {% endfor %}
    {% endwith %}

    {% if th_movie_data %}
        <table class="table">
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            <thead>
                <tr class="table__header">
                    <th class="table__cell table__cell--header">Title</th>
                    <th class="table__cell table__cell--header">Release Date</th>
                    <th class="table__cell table__cell--header"></th>
                </tr>
            </thead>
            <tbody>
                {% for movie in th_movie_data %}
                    <tr>
                        <td class="table__cell">
                            <p class="table__movieTitle">{{ movie.title }}</p>
                            <p class="table__movieDirector">By {{ movie.director }}</p>
                        </td>
                        <td class="table__cell">{{ movie.year }}</td>
                        <td class="table__cell"><a href="{{ url_for('pages.movie', _id = movie._id) }}" class="table__link">View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="table__empty">You haven't added any movies yet. <a href="{{ url_for('pages.add_movie') }}" class="link">Add one!</a></p>
    {% endif %}
    
    <a href="{{ url_for('pages.add_movie') }}" class="button button--add">
        <span>+</span>
    </a>

{% endblock %}

movie_library/templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}
{% from "macros/svgs.html" import star, pencil, moon, sun %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        {{ header (session.get('email'), session.get('theme')) }}
        <main class="main">
            {% block main_content %} {% endblock %}
        </main>
        {{ footer () }}
    </body>
</html>

movie_library/templates/login.html
{% from "macros/fields.html" import render_text_field, render_area_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        
        <div class="form__container">
            {{ th_form.hidden_tag() }}

            {{ render_text_field(th_form.email) }}
            {{ render_text_field(th_form.password) }}
    
            <span class="form__small">
                Not have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ th_form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
    <meta property="og:url"           content="{{ th_link_qr }}" />
    <meta property="og:title"         content="{{ title }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movie_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie__header">
        <div class="header__row">
            <div class="movie__name">
                <h1>{{ th_movie.title }}</h1>
                <div class="movie__rating">
                    {% for i in range(5) %}
                    <a class="rating__link " href="{{ url_for('pages.rating', _id = th_movie._id, rating = i+1) }}">
                      {{ star("star "+ ('star--filled' if th_movie.rating > i else '')) }}
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="movie__watched">
                {% if th_movie.last_watched %}
                    <p>
                        Last watched: <a href="{{ url_for('pages.watch_date', _id = th_movie._id) }}" class="watched__link">
                            <time datetime="{{ th_movie.last_watched }}">{{th_movie.last_watched}}</time>
                        </a>
                    </p>
                {% else %}
                    <p><a href="{{ url_for('pages.watch_date', _id = th_movie._id) }}" class="watched__link">Not watched yet</a></p>
                {% endif %}

                {% if th_check %}
                <a class="movie__edit" href="{{ url_for('pages.edit_movie', _id = th_movie._id) }}">Edit {{ pencil("pencil") }}</a>
                {% else %}
                <p class="prohibit_message"></p>
                <a class="movie__edit movie__edit_prohibit" href="#">Edit {{ pencil("pencil") }}</a>
                {% endif %}
            </div>
        </div>
        <div class="header__row">
            <ul class="movie__tags">
            {% for tag in th_movie.tags %}
                <li class="movie__tag">{{ tag }}</li>
            {% endfor %}
            </ul>
        </div>
    </header>

    {% if th_movie.video_link %}
    <iframe
        class="movie__video"
        src="{{ th_movie.video_link }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if th_movie.description %}
    <p class="movie__description">{{ th_movie.description }}</p>
    {% else %}
    <p class="movie__description">No description yet. <a class="link" href="#">Add one?</a></p>
    {% endif %}

  <div class="movie__meta">
      {% if th_movie.cast %}
          <div class="movie__casting">
              <h2>Casting</h2>
              <ul class="list">
              {% for actor in th_movie.cast %}
                  <li class="list__item">{{ actor }}</li>
              {% endfor %}
              <ul>
          </div>
      {% endif %}
      {% if th_movie.series | length %}
          <div class="movie__series">
              <h2>Series</h2>
              <ul class="list">
              {% for movie_in_series in th_movie.series %}
                  <li class="list__item">{{ movie_in_series }}</li>
              {% endfor %}
              <ul>
          </div>
      {% endif %}
  </div>

  <div class="movie__qr">
    <p class="movie__qr_share">Share movie QR code to your friend!</p>
    <img 
    src="{{ qrcode(th_link_qr) }}" 
    alt="Your movie qr code" 
    class = "qr__img">
    {% set email_split = session.get('email').split('@') %}
    <a href="{{ qrcode(th_link_qr) }}" download="{{th_slugified_title + '-' + email_split[0]}}.jpg" class="button button--share">Download QR</a>

    <div id="fb-root"></div>
    <script async defer 
    crossorigin="anonymous" 
    src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v14.0" 
    nonce="NvKB0rkm">
    </script>
    
    <div class="fb-share-button" 
    data-href="{{th_link_qr}}" 
    data-layout="button" data-size="large">
        <a target="_blank" 
        href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" 
        class="fb-xfbml-parse-ignore">Share
        </a>
    </div>
  </div>
</div>

<script>
    document.getElementsByClassName("movie__edit_prohibit")[0].addEventListener("click", function() {
        alert("Cannot edit due to lack of ownership!");
    });   

    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));


</script>
{% endblock %}

movie_library/templates/new_movie.html
{% from "macros/fields.html" import render_text_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<form action="{{ url_for ('pages.add_movie') }}" class="form" novalidate method="post">
  <div class="form__container">
    {{ form.hidden_tag() }}
    {{ render_text_field(form.title) }}
    {{ render_text_field(form.director) }}
    {{ render_text_field(form.year) }}
    <div>
      {{ form.submit(class_="button button--form")}}
    </div>
  </div>
</form>

{% endblock %}

movie_library/templates/register.html
{% from "macros/fields.html" import render_text_field, render_area_field %}
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        
        <div class="form__container">
            {{ th_form.hidden_tag() }}

            {{ render_text_field(th_form.email) }}
            {{ render_text_field(th_form.password) }}
            {{ render_text_field(th_form.confirm_password) }}
    
            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
            </span>
    
            <div>
                {{ th_form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}